version: "3"
services:
    app:
        image: webdevops/php-nginx-dev:7.1
        ports:
            - "8082:80"
        volumes:
            - /var/www/src:/app
        environment:
            - PHP_DEBUGGER=xdebug
            - PHP_DISPLAY_ERRORS=1
            - PHP_DATE_TIMEZONE=Asia/Ho_Chi_Minh
            - WEB_DOCUMENT_ROOT=/app/public
    nodejs:
        image: node:8
        stdin_open: true
        volumes:
            - /var/www/src:/app
